# Dependency Installation and Caching
name: Setup Dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # Run weekly to refresh cache
    - cron: '0 2 * * 0'

jobs:
  setup-dependencies:
    runs-on: ubuntu-22.04
    
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Cache Odoo and dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            /tmp/odoo
            /tmp/odoo-requirements
          key: ${{ runner.os }}-odoo-18.0-${{ hashFiles('**/requirements.txt') }}-v3
          restore-keys: |
            ${{ runner.os }}-odoo-18.0-
            ${{ runner.os }}-odoo-
            
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpq-dev \
            python3-dev \
            libxml2-dev \
            libxslt1-dev \
            libldap2-dev \
            libsasl2-dev \
            libjpeg-dev \
            libfreetype6-dev \
            liblcms2-dev \
            libwebp-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libxcb1-dev
            
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          
          # Core dependencies
          pip install psycopg2-binary babel "lxml[html_clean]" pillow reportlab \
          python-dateutil pytz requests werkzeug jinja2 passlib decorator docutils \
          gevent greenlet markupsafe num2words ofxparse polib psutil python-stdnum \
          qrcode vobject xlsxwriter xlwt zeep pypdf freezegun rjsmin
          
          # Development and testing dependencies
          pip install pylint-odoo coverage pytest
          
      - name: Setup Odoo
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "📥 Setting up Odoo 18.0..."
          
          if [ ! -d "/tmp/odoo" ]; then
            git clone --depth 1 --branch 18.0 https://github.com/odoo/odoo.git /tmp/odoo
          fi
          
          # Install Odoo requirements
          if [ -f "/tmp/odoo/requirements.txt" ]; then
            pip install -r /tmp/odoo/requirements.txt
          fi
          
          # Create requirements cache
          pip freeze > /tmp/odoo-requirements/requirements.txt
          
      - name: Verify Odoo installation
        run: |
          echo "🔍 Verifying Odoo installation..."
          
          # Test Odoo import
          python -c "
          import sys
          sys.path.insert(0, '/tmp/odoo')
          try:
              import odoo
              print('✅ Odoo import successful')
              print(f'📍 Odoo version: {odoo.release.version}')
          except ImportError as e:
              print(f'❌ Odoo import failed: {e}')
              sys.exit(1)
          "
                    
                - name: Cache summary
                  run: |
                    echo "📊 Cache Summary:"
                    echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
                    echo "Odoo location: /tmp/odoo"
                    echo "Requirements cached: $([ -f /tmp/odoo-requirements/requirements.txt ] && echo 'Yes' || echo 'No')"
                    
                    if [ -d "/tmp/odoo" ]; then
                      echo "Odoo size: $(du -sh /tmp/odoo | cut -f1)"
                    fi